import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function cities() {
  console.log('🔃 Starting Seeds Cities.seeds.ts...');
  await prisma.cities.deleteMany();
  await prisma.$executeRaw`ALTER TABLE Cities AUTO_INCREMENT = 1`;

  const source = [
    { name: 'Mataram', provinceId: 1 },
    { name: 'Bima', provinceId: 1 },
    { name: 'Dompu', provinceId: 1 },
    { name: 'Lombok Tengah', provinceId: 1 },
    { name: 'Lombok Timur', provinceId: 1 },
    { name: 'Sumbawa Besar', provinceId: 1 },
    { name: 'Sumbawa', provinceId: 1 },
    { name: 'Lombok Barat', provinceId: 1 },
    { name: 'Lombok Utara', provinceId: 1 },
    { name: 'Sumbawa Barat', provinceId: 1 },
    { name: 'Ambon', provinceId: 3 },
    { name: 'Maluku Tengah', provinceId: 3 },
    { name: 'Maluku', provinceId: 3 },
    { name: 'Maluku Tenggara', provinceId: 3 },
    { name: 'Tual', provinceId: 3 },
    { name: 'Buru', provinceId: 3 },
    { name: 'Buru Selatan', provinceId: 3 },
    { name: 'Dobo', provinceId: 3 },
    { name: 'Kepulauan Aru', provinceId: 3 },
    { name: 'Piru', provinceId: 3 },
    { name: 'Seram Bagian Barat', provinceId: 3 },
    { name: 'Dataran Hunimoa', provinceId: 3 },
    { name: 'Seram Bagian Timur', provinceId: 3 },
    { name: 'Maluku Barat Daya', provinceId: 3 },
    { name: 'Maluku Tenggara Barat', provinceId: 3 },
    { name: 'Luser', provinceId: 3 },
    { name: 'Mola', provinceId: 3 },
    { name: 'Serwaru', provinceId: 3 },
    { name: 'Banjarmasin', provinceId: 4 },
    { name: 'Hulu Sungai Tengah', provinceId: 4 },
    { name: 'Batang Alai Tengah', provinceId: 4 },
    { name: 'Hulu Sungai Selatan', provinceId: 4 },
    { name: 'Kota Baru', provinceId: 4 },
    { name: 'Kotabaru', provinceId: 4 },
    { name: 'Tabalong', provinceId: 4 },
    { name: 'Banjarbaru', provinceId: 4 },
    { name: 'Amuntai', provinceId: 4 },
    { name: 'Hulu Sungai Utara', provinceId: 4 },
    { name: 'Barito Kuala', provinceId: 4 },
    { name: 'Banjar', provinceId: 4 },
    { name: 'Simpang Empat', provinceId: 4 },
    { name: 'Tanah Laut', provinceId: 4 },
    { name: 'Rantau', provinceId: 4 },
    { name: 'Tapin', provinceId: 4 },
    { name: 'Muara Teweh', provinceId: 4 },
    { name: 'Barito Utara', provinceId: 5 },
    { name: 'Tamiang Layang', provinceId: 4 },
    { name: 'Barito Timur', provinceId: 5 },
    { name: 'Puruk Cahu', provinceId: 4 },
    { name: 'Murung Raya', provinceId: 5 },
    { name: 'Buntok', provinceId: 4 },
    { name: 'Barito Selatan', provinceId: 5 },
    { name: 'Balangan', provinceId: 4 },
    { name: 'Tanah Bumbu', provinceId: 4 },
    { name: 'Bandung', provinceId: 6 },
    { name: 'Cimahi', provinceId: 6 },
    { name: 'Sumedang', provinceId: 6 },
    { name: 'Garut, Kab. Garut', provinceId: 6 },
    { name: 'Garut', provinceId: 6 },
    { name: 'Bandung Barat', provinceId: 6 },
    { name: 'Cimareme', provinceId: 6 },
    { name: 'Cianjur', provinceId: 6 },
    { name: 'Bekasi', provinceId: 6 },
    { name: 'Bengkulu', provinceId: 7 },
    { name: 'Bengkulu Utara', provinceId: 7 },
    { name: 'Bengkulu Tengah', provinceId: 7 },
    { name: 'Rejang Lebong', provinceId: 7 },
    { name: 'Bengkulu Selatan', provinceId: 7 },
    { name: 'Kaur', provinceId: 7 },
    { name: 'Kepahiang', provinceId: 7 },
    { name: 'Lebong', provinceId: 7 },
    { name: 'Muko-Muko', provinceId: 7 },
    { name: 'Muko Muko', provinceId: 7 },
    { name: 'Muko-Muko Selatan', provinceId: 7 },
    { name: 'Tais', provinceId: 7 },
    { name: 'Seluma', provinceId: 7 },
    { name: 'Bogor', provinceId: 6 },
    { name: 'Balikpapan', provinceId: 8 },
    { name: 'Kutai Kartanegara', provinceId: 8 },
    { name: 'Paser', provinceId: 8 },
    { name: 'Berau', provinceId: 8 },
    { name: 'Tubaan', provinceId: 8 },
    { name: 'Penajam Paser Utara', provinceId: 8 },
    { name: 'Bontang', provinceId: 8 },
    { name: 'Sangatta', provinceId: 8 },
    { name: 'Kutai Timur', provinceId: 8 },
    { name: 'Sangkima', provinceId: 8 },
    { name: 'Swarga Bara', provinceId: 8 },
    { name: 'Singa Gembara', provinceId: 8 },
    { name: 'Batam', provinceId: 9 },
    { name: 'Daik', provinceId: 9 },
    { name: 'Lingga', provinceId: 9 },
    { name: 'Kepulauan Riau', provinceId: 9 },
    { name: 'Natuna', provinceId: 9 },
    { name: 'Kepulauan Anambas', provinceId: 9 },
    { name: 'Karimun', provinceId: 9 },
    { name: 'Banda Aceh', provinceId: 10 },
    { name: 'Langsa', provinceId: 10 },
    { name: 'Langsa Teungoh', provinceId: 10 },
    { name: 'Lhokseumawe', provinceId: 10 },
    { name: 'Aceh Besar', provinceId: 10 },
    { name: 'Bireuen', provinceId: 10 },
    { name: 'Kutacane', provinceId: 10 },
    { name: 'Aceh Tenggara', provinceId: 10 },
    { name: 'Meulaboh', provinceId: 10 },
    { name: 'Aceh Barat', provinceId: 10 },
    { name: 'Pidie', provinceId: 10 },
    { name: 'Takengon', provinceId: 10 },
    { name: 'Aceh Tengah', provinceId: 10 },
    { name: 'Aceh Selatan', provinceId: 10 },
    { name: 'Sabang', provinceId: 10 },
    { name: 'Aceh Barat Daya', provinceId: 10 },
    { name: 'Aceh Jaya', provinceId: 10 },
    { name: 'Aceh Singkil', provinceId: 10 },
    { name: 'Suro Baru', provinceId: 10 },
    { name: 'Aceh Tamiang', provinceId: 10 },
    { name: 'Aceh Timur', provinceId: 10 },
    { name: 'Aceh Utara', provinceId: 10 },
    { name: 'Simpang Tiga Redelon', provinceId: 10 },
    { name: 'Bener Meriah', provinceId: 10 },
    { name: 'Syiah Kuala', provinceId: 10 },
    { name: 'Gayo Lues', provinceId: 10 },
    { name: 'Pantan Jaya', provinceId: 10 },
    { name: 'Nagan Raya', provinceId: 10 },
    { name: 'Pidie Jaya', provinceId: 10 },
    { name: 'Sinabang', provinceId: 10 },
    { name: 'Simeulue', provinceId: 10 },
    { name: 'Subulussalam', provinceId: 10 },
    { name: 'Cirebon', provinceId: 6 },
    { name: 'Cirebon Barat', provinceId: 6 },
    { name: 'Indramayu', provinceId: 6 },
    { name: 'Kuningan', provinceId: 6 },
    { name: 'Majalengka', provinceId: 6 },
    { name: 'DKI Jakarta', provinceId: 11 },
    { name: 'Jakarta Barat', provinceId: 11 },
    { name: 'Jakarta Selatan', provinceId: 11 },
    { name: 'Jakarta Pusat', provinceId: 11 },
    { name: 'Jakarta Utara', provinceId: 11 },
    { name: 'Jakarta Timur', provinceId: 11 },
    { name: 'Pulau Pramuka', provinceId: 11 },
    { name: 'Kepulauan Seribu', provinceId: 11 },
    { name: 'Cikarang', provinceId: 6 },
    { name: 'Cilegon', provinceId: 12 },
    { name: 'Pandeglang', provinceId: 12 },
    { name: 'Cadas Sari', provinceId: 12 },
    { name: 'Karangtanjung', provinceId: 12 },
    { name: 'Lebak', provinceId: 12 },
    { name: 'Serang', provinceId: 12 },
    { name: 'Cilacap', provinceId: 13 },
    { name: 'Jambi', provinceId: 14 },
    { name: 'Kualatungkal', provinceId: 14 },
    { name: 'Tanjung Jabung Barat', provinceId: 14 },
    { name: 'Merangin', provinceId: 14 },
    { name: 'Batang Hari', provinceId: 14 },
    { name: 'Muara Bungo', provinceId: 14 },
    { name: 'Bungo', provinceId: 14 },
    { name: 'Sungaipenuh', provinceId: 14 },
    { name: 'Kerinci', provinceId: 14 },
    { name: 'Sengeti', provinceId: 14 },
    { name: 'Muaro Jambi', provinceId: 14 },
    { name: 'Sarolangun', provinceId: 14 },
    { name: 'Muara Sabak', provinceId: 14 },
    { name: 'Tanjung Jabung Timur', provinceId: 14 },
    { name: 'Tebo', provinceId: 14 },
    { name: 'Jayapura', provinceId: 15 },
    { name: 'Biak Numfor', provinceId: 15 },
    { name: 'Merauke', provinceId: 15 },
    { name: 'Nabire', provinceId: 15 },
    { name: 'Dogiyai', provinceId: 15 },
    { name: 'Serui', provinceId: 15 },
    { name: 'Kepulauan Yapen', provinceId: 15 },
    { name: 'Jayawijaya', provinceId: 15 },
    { name: 'Kelila', provinceId: 15 },
    { name: 'Lanny Jaya', provinceId: 15 },
    { name: 'Yalimo', provinceId: 15 },
    { name: 'Nduga', provinceId: 15 },
    { name: 'Mamberamo Tengah', provinceId: 15 },
    { name: 'Asmat', provinceId: 15 },
    { name: 'Tanah Merah/ Boven Digoel', provinceId: 15 },
    { name: 'Boven Digoel', provinceId: 15 },
    { name: 'Keerom', provinceId: 15 },
    { name: 'Kepi', provinceId: 15 },
    { name: 'Mappi', provinceId: 15 },
    { name: 'Intan Jaya', provinceId: 15 },
    { name: 'Paniai', provinceId: 15 },
    { name: 'Deiyai', provinceId: 15 },
    { name: 'Pegunungan Bintang', provinceId: 15 },
    { name: 'Puncak Jaya', provinceId: 15 },
    { name: 'Puncak', provinceId: 15 },
    { name: 'Sarmi', provinceId: 15 },
    { name: 'Sorendiweri', provinceId: 15 },
    { name: 'Supiori', provinceId: 15 },
    { name: 'Tolikara', provinceId: 15 },
    { name: 'Botawa', provinceId: 15 },
    { name: 'Waropen', provinceId: 15 },
    { name: 'Yahukimo', provinceId: 15 },
    { name: 'Burmeso', provinceId: 15 },
    { name: 'Mamberamo Raya', provinceId: 15 },
    { name: 'Depok', provinceId: 6 },
    { name: 'Cibubur', provinceId: 6 },
    { name: 'Denpasar', provinceId: 16 },
    { name: 'Amlapura', provinceId: 16 },
    { name: 'Karangasem', provinceId: 16 },
    { name: 'Bangli', provinceId: 16 },
    { name: 'Gianyar', provinceId: 16 },
    { name: 'Jembrana', provinceId: 16 },
    { name: 'Semarapura', provinceId: 16 },
    { name: 'Klungkung', provinceId: 16 },
    { name: 'Singaraja', provinceId: 16 },
    { name: 'Buleleng', provinceId: 16 },
    { name: 'Tabanan', provinceId: 16 },
    { name: 'Badung', provinceId: 16 },
    { name: 'Legian', provinceId: 16 },
    { name: 'Ngurah Rai', provinceId: 16 },
    { name: 'Sanur', provinceId: 16 },
    { name: 'Jimbaran', provinceId: 16 },
    { name: 'Nusa Dua', provinceId: 16 },
    { name: 'Toba Samosir', provinceId: 17 },
    { name: 'Gunungsitoli', provinceId: 17 },
    { name: 'Nias', provinceId: 17 },
    { name: 'Nias Barat', provinceId: 17 },
    { name: 'Nias Selatan', provinceId: 17 },
    { name: 'Nias Utara', provinceId: 17 },
    { name: 'Lahewa', provinceId: 17 },
    { name: 'Sibolga', provinceId: 17 },
    { name: 'Tapanuli Tengah', provinceId: 17 },
    { name: 'Padang Sidempuan', provinceId: 17 },
    { name: 'Tapanuli Selatan', provinceId: 17 },
    { name: 'Tapanuli Utara', provinceId: 17 },
    { name: 'Gunung Tua', provinceId: 17 },
    { name: 'Padang Lawas Utara', provinceId: 17 },
    { name: 'Batang Onang', provinceId: 17 },
    { name: 'Dolok', provinceId: 17 },
    { name: 'Dolok Sigompulon', provinceId: 17 },
    { name: 'Halongonan', provinceId: 17 },
    { name: 'Padang Bolak', provinceId: 17 },
    { name: 'Padang Bolak Julu', provinceId: 17 },
    { name: 'Portibi', provinceId: 17 },
    { name: 'Humbang Hasundutan', provinceId: 17 },
    { name: 'Mandailing Natal', provinceId: 17 },
    { name: 'Panyabungan Kota', provinceId: 17 },
    { name: 'Sibuhuan', provinceId: 17 },
    { name: 'Padang Lawas', provinceId: 17 },
    { name: 'Ulu Barumun', provinceId: 17 },
    { name: 'Barumun', provinceId: 17 },
    { name: 'Batang Lubu Sutam', provinceId: 17 },
    { name: 'Huristak', provinceId: 17 },
    { name: 'Huta Raja Tinggi', provinceId: 17 },
    { name: 'Lubuk Barumun', provinceId: 17 },
    { name: 'Barumun Tengah', provinceId: 17 },
    { name: 'Gorontalo', provinceId: 18 },
    { name: 'Gorontalo Utara', provinceId: 18 },
    { name: 'Boalemo', provinceId: 18 },
    { name: 'Bone Bolango', provinceId: 18 },
    { name: 'Pohuwato', provinceId: 18 },
    { name: 'Jember', provinceId: 19 },
    { name: 'Banyuwangi', provinceId: 19 },
    { name: 'Bondowoso', provinceId: 19 },
    { name: 'Kediri', provinceId: 19 },
    { name: 'Yogyakarta', provinceId: 20 },
    { name: 'Bantul', provinceId: 20 },
    { name: 'Sleman', provinceId: 20 },
    { name: 'Kulon Progo', provinceId: 20 },
    { name: 'Gunung Kidul', provinceId: 20 },
    { name: 'Kendari', provinceId: 21 },
    { name: 'Kendar', provinceId: 21 },
    { name: 'Bau - Bau', provinceId: 21 },
    { name: 'Bau-Bau', provinceId: 21 },
    { name: 'Kolaka', provinceId: 21 },
    { name: 'Kolaka Timur', provinceId: 21 },
    { name: 'Raha', provinceId: 21 },
    { name: 'Buton Utara', provinceId: 21 },
    { name: 'Muna', provinceId: 21 },
    { name: 'Muna Barat', provinceId: 21 },
    { name: 'Tikep', provinceId: 21 },
    { name: 'Wakorumba', provinceId: 21 },
    { name: 'Konawe', provinceId: 21 },
    { name: 'Konawe Utara', provinceId: 21 },
    { name: 'Wawonii', provinceId: 21 },
    { name: 'Waworete', provinceId: 21 },
    { name: 'Bombana', provinceId: 21 },
    { name: 'Buton', provinceId: 21 },
    { name: 'Buton Selatan', provinceId: 21 },
    { name: 'Buton Tengah', provinceId: 21 },
    { name: 'Buranga', provinceId: 21 },
    { name: 'Kolaka Utara', provinceId: 21 },
    { name: 'Konawe Selatan', provinceId: 21 },
    { name: 'Wakatobi', provinceId: 21 },
    { name: 'Konawe Kepulauan', provinceId: 21 },
    { name: 'Kupang', provinceId: 22 },
    { name: 'Waibakul', provinceId: 22 },
    { name: 'Sumba Tengah', provinceId: 22 },
    { name: 'Belu', provinceId: 22 },
    { name: 'Malaka', provinceId: 22 },
    { name: 'Kalabahi', provinceId: 22 },
    { name: 'Alor', provinceId: 22 },
    { name: 'Timor Tengah Utara', provinceId: 22 },
    { name: 'Flores Timur', provinceId: 22 },
    { name: 'Maumere', provinceId: 22 },
    { name: 'Sikka', provinceId: 22 },
    { name: 'Manggarai', provinceId: 22 },
    { name: 'Lambaleda', provinceId: 22 },
    { name: 'Komba', provinceId: 22 },
    { name: 'Mborong', provinceId: 22 },
    { name: 'Ponco Ranaka', provinceId: 22 },
    { name: 'Sambi Rambas', provinceId: 22 },
    { name: 'Soe', provinceId: 22 },
    { name: 'Timor Tengah Selatan', provinceId: 22 },
    { name: 'Ende', provinceId: 22 },
    { name: 'Ngada', provinceId: 22 },
    { name: 'Ngada Bawa', provinceId: 22 },
    { name: 'Wogomang Ulewa', provinceId: 22 },
    { name: 'Sumba Timur', provinceId: 22 },
    { name: 'Sumba Barat', provinceId: 22 },
    { name: 'Laratama', provinceId: 22 },
    { name: 'Walakaka', provinceId: 22 },
    { name: 'Labuan Bajo', provinceId: 22 },
    { name: 'Manggarai Barat', provinceId: 22 },
    { name: 'Manggarai Timur', provinceId: 22 },
    { name: 'Mbay', provinceId: 22 },
    { name: 'Nagekeo', provinceId: 22 },
    { name: 'Baa', provinceId: 22 },
    { name: 'Rote Ndao', provinceId: 22 },
    { name: 'Tambolaka', provinceId: 22 },
    { name: 'Sumba Barat Daya', provinceId: 22 },
    { name: 'Lembata', provinceId: 22 },
    { name: 'Oelamasi', provinceId: 22 },
    { name: 'Sabu Raijua', provinceId: 22 },
    { name: 'Karawang', provinceId: 6 },
    { name: 'Manado', provinceId: 23 },
    { name: 'Kotamobagu', provinceId: 23 },
    { name: 'Bolaang Mongondow Utara', provinceId: 23 },
    { name: 'Bolaang Mongondow', provinceId: 23 },
    { name: 'Bolaang Itang', provinceId: 23 },
    { name: 'Bolaang Mongondow Selatan', provinceId: 23 },
    { name: 'Bolaang Mongondow Timur', provinceId: 23 },
    { name: 'Passi', provinceId: 23 },
    { name: 'Kepulauan Sangihe', provinceId: 23 },
    { name: 'Kepulauan Siau Tagulandang Biaro (Sitaro)', provinceId: 23 },
    { name: 'Tondano', provinceId: 23 },
    { name: 'Minahasa', provinceId: 23 },
    { name: 'Bitung', provinceId: 23 },
    { name: 'Boroko', provinceId: 23 },
    { name: 'Bintauna', provinceId: 23 },
    { name: 'Kaidipang', provinceId: 23 },
    { name: 'Pinogaluman', provinceId: 23 },
    { name: 'Kepulauan Talaud', provinceId: 23 },
    { name: 'Minahasa Utara', provinceId: 23 },
    { name: 'Minahasa Selatan', provinceId: 23 },
    { name: 'Tombasian', provinceId: 23 },
    { name: 'Minahasa Tenggara', provinceId: 23 },
    { name: 'Tomohon', provinceId: 23 },
    { name: 'Madiun', provinceId: 19 },
    { name: 'Caruban', provinceId: 19 },
    { name: 'Magetan', provinceId: 19 },
    { name: 'Kartoharjo', provinceId: 19 },
    { name: 'Ngawi', provinceId: 19 },
    { name: 'Kendungan', provinceId: 19 },
    { name: 'Pacitan', provinceId: 19 },
    { name: 'Ponorogo', provinceId: 19 },
    { name: 'Mojokerto', provinceId: 19 },
    { name: 'Jombang', provinceId: 19 },
    { name: 'Nganjuk', provinceId: 19 },
    { name: 'Malang', provinceId: 19 },
    { name: 'Blitar', provinceId: 19 },
    { name: 'Batu', provinceId: 19 },
    { name: 'Probolinggo', provinceId: 19 },
    { name: 'Lumajang', provinceId: 19 },
    { name: 'Situbondo', provinceId: 19 },
    { name: 'Medan', provinceId: 17 },
    { name: 'Kisaran', provinceId: 17 },
    { name: 'Asahan', provinceId: 17 },
    { name: 'Dairi', provinceId: 17 },
    { name: 'Deli Serdang', provinceId: 17 },
    { name: 'Binjai', provinceId: 17 },
    { name: 'Pematang Raya', provinceId: 17 },
    { name: 'Simalungun', provinceId: 17 },
    { name: 'Rantau Prapat', provinceId: 17 },
    { name: 'Labuhanbatu Utara', provinceId: 17 },
    { name: 'Labuhanbatu', provinceId: 17 },
    { name: 'Labuhanbatu Selatan', provinceId: 17 },
    { name: 'Kualuh Selatan', provinceId: 17 },
    { name: 'Karo', provinceId: 17 },
    { name: 'Langkat', provinceId: 17 },
    { name: 'Serdang Bedagai', provinceId: 17 },
    { name: 'Tebing Tinggi', provinceId: 17 },
    { name: 'Batu Bara', provinceId: 17 },
    { name: 'Pakpak Bharat', provinceId: 17 },
    { name: 'Samosir', provinceId: 17 },
    { name: 'Tanjung Balai', provinceId: 17 },
    { name: 'Pematang Siantar', provinceId: 17 },
    { name: 'Magelang', provinceId: 13 },
    { name: 'Kebumen', provinceId: 13 },
    { name: 'Wonosobo', provinceId: 13 },
    { name: 'Purworejo', provinceId: 13 },
    { name: 'Temanggung', provinceId: 13 },
    { name: 'Padang', provinceId: 24 },
    { name: 'Batu Sangkar', provinceId: 24 },
    { name: 'Tanah Datar', provinceId: 24 },
    { name: 'Bukit Tinggi', provinceId: 24 },
    { name: 'Bukittinggi', provinceId: 24 },
    { name: 'Pasaman', provinceId: 24 },
    { name: 'Painan', provinceId: 24 },
    { name: 'Pesisir Selatan', provinceId: 24 },
    { name: 'Pariaman', provinceId: 24 },
    { name: 'Padang Pariaman', provinceId: 24 },
    { name: 'Lima Puluh Kota', provinceId: 24 },
    { name: 'Payakumbuh', provinceId: 24 },
    { name: 'Sawahlunto', provinceId: 24 },
    { name: 'Sawah Lunto', provinceId: 24 },
    { name: 'Solok', provinceId: 24 },
    { name: 'Padang Panjang', provinceId: 24 },
    { name: 'Dharmasraya', provinceId: 24 },
    { name: 'Sarilamak', provinceId: 24 },
    { name: 'Tuapejat', provinceId: 24 },
    { name: 'Kepulauan Mentawai', provinceId: 24 },
    { name: 'Sipora', provinceId: 24 },
    { name: 'Pasaman Barat', provinceId: 24 },
    { name: 'Ranah Balingka', provinceId: 24 },
    { name: 'Ranah Pesisir', provinceId: 24 },
    { name: 'Arosuka', provinceId: 24 },
    { name: 'Padang Aro', provinceId: 24 },
    { name: 'Solok Selatan', provinceId: 24 },
    { name: 'Muaro Sijunjung', provinceId: 24 },
    { name: 'Sijunjung', provinceId: 24 },
    { name: 'Agam', provinceId: 24 },
    { name: 'Pangkal Pinang', provinceId: 25 },
    { name: 'Bangka', provinceId: 25 },
    { name: 'Bangka Barat', provinceId: 25 },
    { name: 'Bangka Tengah', provinceId: 25 },
    { name: 'Bangka Selatan', provinceId: 25 },
    { name: 'Pekanbaru', provinceId: 26 },
    { name: 'Dumai', provinceId: 26 },
    { name: 'Kampar', provinceId: 26 },
    { name: 'Bengkalis', provinceId: 26 },
    { name: 'Duri Mandau', provinceId: 26 },
    { name: 'Indragiri Hulu', provinceId: 26 },
    { name: 'Indragiri Hilir', provinceId: 26 },
    { name: 'Bagan Siapi-api', provinceId: 26 },
    { name: 'Rokan Hilir', provinceId: 26 },
    { name: 'Teluk Kuantan', provinceId: 26 },
    { name: 'Kuantan Singingi', provinceId: 26 },
    { name: 'Pelalawan', provinceId: 26 },
    { name: 'Sorek', provinceId: 26 },
    { name: 'Pasir Pangaraian', provinceId: 26 },
    { name: 'Rokan Hulu', provinceId: 26 },
    { name: 'Tembusai', provinceId: 26 },
    { name: 'Tembusai Utara', provinceId: 26 },
    { name: 'Siak Indrapura', provinceId: 26 },
    { name: 'Siak', provinceId: 26 },
    { name: 'Meranti', provinceId: 26 },
    { name: 'Selat Panjang', provinceId: 26 },
    { name: 'Kepulauan Meranti', provinceId: 26 },
    { name: 'Palangkaraya', provinceId: 5 },
    { name: 'Palangka Raya', provinceId: 5 },
    { name: 'Kasongan', provinceId: 5 },
    { name: 'Katingan', provinceId: 5 },
    { name: 'Kuala Kapuas', provinceId: 5 },
    { name: 'Kapuas', provinceId: 5 },
    { name: 'Kuala Kurun', provinceId: 5 },
    { name: 'Gunung Mas', provinceId: 5 },
    { name: 'Kuala Pembuang', provinceId: 5 },
    { name: 'Seruyan', provinceId: 5 },
    { name: 'Pangkalan Bun', provinceId: 5 },
    { name: 'Kotawaringin Barat', provinceId: 5 },
    { name: 'Sampit', provinceId: 5 },
    { name: 'Kotawaringin Timur', provinceId: 5 },
    { name: 'Nanga Bulik', provinceId: 5 },
    { name: 'Lamandau', provinceId: 5 },
    { name: 'Pulang Pisau', provinceId: 5 },
    { name: 'Sukamara', provinceId: 5 },
    { name: 'Palembang', provinceId: 27 },
    { name: 'Muara Beliti Baru', provinceId: 27 },
    { name: 'Musi Rawas', provinceId: 27 },
    { name: 'Musi Rawas Utara', provinceId: 27 },
    { name: 'Muara Rupit', provinceId: 27 },
    { name: 'Baturaja', provinceId: 27 },
    { name: 'Ogan Komering Ulu', provinceId: 27 },
    { name: 'Ogan Komering Ilir', provinceId: 27 },
    { name: 'Pematang Panggang', provinceId: 27 },
    { name: 'Lahat', provinceId: 27 },
    { name: 'Merapi', provinceId: 27 },
    { name: 'Tanjung Sakti', provinceId: 27 },
    { name: 'Muara Enim', provinceId: 27 },
    { name: 'Penukal Abab Lematang Ilir', provinceId: 27 },
    { name: 'Pagar Alam', provinceId: 27 },
    { name: 'Prabumulih', provinceId: 27 },
    { name: 'Musi Banyuasin', provinceId: 27 },
    { name: 'Pangkalan Balai', provinceId: 27 },
    { name: 'Banyuasin', provinceId: 27 },
    { name: 'Empat Lawang', provinceId: 27 },
    { name: 'Ogan Ilir', provinceId: 27 },
    { name: 'Ogan Komering Ulu Timur', provinceId: 27 },
    { name: 'Ogan Komering Ulu Selatan', provinceId: 27 },
    { name: 'Lubuk Linggau', provinceId: 27 },
    { name: 'Palu', provinceId: 28 },
    { name: 'Banggai', provinceId: 28 },
    { name: 'Poso', provinceId: 28 },
    { name: 'Toli-Toli', provinceId: 28 },
    { name: 'Banggai Laut', provinceId: 28 },
    { name: 'Banggai Kepulauan', provinceId: 28 },
    { name: 'Lo Bangkurung', provinceId: 28 },
    { name: 'Buol', provinceId: 28 },
    { name: 'Donggala', provinceId: 28 },
    { name: 'Dolo', provinceId: 28 },
    { name: 'Sigi', provinceId: 28 },
    { name: 'Bungku', provinceId: 28 },
    { name: 'Morowali', provinceId: 28 },
    { name: 'Morowali Utara', provinceId: 28 },
    { name: 'Parigi Moutong', provinceId: 28 },
    { name: 'Tojo Una-Una', provinceId: 28 },
    { name: 'Pontianak', provinceId: 29 },
    { name: 'Ketapang', provinceId: 29 },
    { name: 'Sanggau', provinceId: 29 },
    { name: 'Singkawang', provinceId: 29 },
    { name: 'Sintang', provinceId: 29 },
    { name: 'Putussibau', provinceId: 29 },
    { name: 'Kapuas Hulu', provinceId: 29 },
    { name: 'Embai', provinceId: 29 },
    { name: 'Kedamin', provinceId: 29 },
    { name: 'Bengkayang', provinceId: 29 },
    { name: 'Landak', provinceId: 29 },
    { name: 'Melawi', provinceId: 29 },
    { name: 'Ambalau', provinceId: 29 },
    { name: 'Mempawah', provinceId: 29 },
    { name: 'Kubu Raya', provinceId: 29 },
    { name: 'Sambas', provinceId: 29 },
    { name: 'Sekadau', provinceId: 29 },
    { name: 'Kayong Utara', provinceId: 29 },
    { name: 'Pasuruan', provinceId: 19 },
    { name: 'Purwakarta', provinceId: 6 },
    { name: 'Subang', provinceId: 6 },
    { name: 'Samarinda', provinceId: 8 },
    { name: 'Sendawar', provinceId: 8 },
    { name: 'Kutai Barat', provinceId: 8 },
    { name: 'Mahakam Ulu', provinceId: 8 },
    { name: 'Sukabumi', provinceId: 6 },
    { name: 'Surakarta', provinceId: 13 },
    { name: 'Boyolali', provinceId: 13 },
    { name: 'Karanganyar', provinceId: 13 },
    { name: 'Klaten', provinceId: 13 },
    { name: 'Sragen', provinceId: 13 },
    { name: 'Sukoharjo', provinceId: 13 },
    { name: 'Wonogiri', provinceId: 13 },
    { name: 'Sorong', provinceId: 30 },
    { name: 'Tambrauw', provinceId: 30 },
    { name: 'Fakfak', provinceId: 30 },
    { name: 'Kaimana', provinceId: 30 },
    { name: 'Waisai', provinceId: 30 },
    { name: 'Raja Ampat', provinceId: 30 },
    { name: 'Sorong Selatan', provinceId: 30 },
    { name: 'Maybrat', provinceId: 30 },
    { name: 'Teluk Bintuni', provinceId: 30 },
    { name: 'Rasei', provinceId: 30 },
    { name: 'Teluk Wondama', provinceId: 30 },
    { name: 'Manokwari', provinceId: 30 },
    { name: 'Pegunungan Arfak', provinceId: 30 },
    { name: 'Manokwari Selatan', provinceId: 30 },
    { name: 'Semarang', provinceId: 13 },
    { name: 'Jepara', provinceId: 13 },
    { name: 'Kudus', provinceId: 13 },
    { name: 'Pekalongan', provinceId: 13 },
    { name: 'Batang', provinceId: 13 },
    { name: 'Blora', provinceId: 13 },
    { name: 'Bojonegoro', provinceId: 19 },
    { name: 'Demak', provinceId: 13 },
    { name: 'Kendal', provinceId: 13 },
    { name: 'Pati', provinceId: 13 },
    { name: 'Pemalang', provinceId: 13 },
    { name: 'Grobogan', provinceId: 13 },
    { name: 'Rembang', provinceId: 13 },
    { name: 'Salatiga', provinceId: 13 },
    { name: 'Ungaran', provinceId: 13 },
    { name: 'Purbalingga', provinceId: 13 },
    { name: 'Banjarnegara', provinceId: 13 },
    { name: 'Surabaya', provinceId: 19 },
    { name: 'Gresik', provinceId: 19 },
    { name: 'Lamongan', provinceId: 19 },
    { name: 'Bangkalan', provinceId: 19 },
    { name: 'Pamekasan', provinceId: 19 },
    { name: 'Sampang', provinceId: 19 },
    { name: 'Sidoarjo', provinceId: 19 },
    { name: 'Sumenep', provinceId: 19 },
    { name: 'Tuban', provinceId: 19 },
    { name: 'Tulungagung', provinceId: 19 },
    { name: 'Trenggalek', provinceId: 19 },
    { name: 'Tegal', provinceId: 13 },
    { name: 'Brebes', provinceId: 13 },
    { name: 'Purwokerto', provinceId: 13 },
    { name: 'Banyumas', provinceId: 13 },
    { name: 'Tangerang', provinceId: 12 },
    { name: 'Karangtengah', provinceId: 12 },
    { name: 'Tangerang Selatan', provinceId: 12 },
    { name: 'Mimika', provinceId: 15 },
    { name: 'Belitung', provinceId: 25 },
    { name: 'Belitung Timur', provinceId: 25 },
    { name: 'Bandar Lampung', provinceId: 31 },
    { name: 'Lampung Selatan', provinceId: 31 },
    { name: 'Lampung Utara', provinceId: 31 },
    { name: 'Metro', provinceId: 31 },
    { name: 'Liwa', provinceId: 31 },
    { name: 'Lampung Barat', provinceId: 31 },
    { name: 'Pesisir Barat', provinceId: 31 },
    { name: 'Lampung Tengah', provinceId: 31 },
    { name: 'Bandar Jaya', provinceId: 31 },
    { name: 'Lampung Timur', provinceId: 31 },
    { name: 'Way Kanan', provinceId: 31 },
    { name: 'Tulang Bawang', provinceId: 31 },
    { name: 'Mesuji', provinceId: 31 },
    { name: 'Tulang Bawang Barat', provinceId: 31 },
    { name: 'Gunung Terang', provinceId: 31 },
    { name: 'Lambu Kibang', provinceId: 31 },
    { name: 'Kota Agung', provinceId: 31 },
    { name: 'Pringsewu', provinceId: 31 },
    { name: 'Tanggamus', provinceId: 31 },
    { name: 'Pesawaran', provinceId: 31 },
    { name: 'Tanjung Pinang', provinceId: 9 },
    { name: 'Senggarang', provinceId: 9 },
    { name: 'Dompak', provinceId: 9 },
    { name: 'Pulau Penyengat', provinceId: 9 },
    { name: 'Bandar Sri Bintan', provinceId: 9 },
    { name: 'Bintan', provinceId: 9 },
    { name: 'Lagoi', provinceId: 9 },
    { name: 'Tarakan', provinceId: 32 },
    { name: 'Bulungan', provinceId: 32 },
    { name: 'Malinau', provinceId: 32 },
    { name: 'Nunukan', provinceId: 32 },
    { name: 'Tanah Tidung', provinceId: 32 },
    { name: 'Tana Tidung', provinceId: 32 },
    { name: 'Tasikmalaya', provinceId: 6 },
    { name: 'Ciamis', provinceId: 6 },
    { name: 'Pangandaran', provinceId: 6 },
    { name: 'Ternate', provinceId: 33 },
    { name: 'Halmahera Barat', provinceId: 33 },
    { name: 'Labuha', provinceId: 33 },
    { name: 'Halmahera Selatan', provinceId: 33 },
    { name: 'Halmahera Tengah', provinceId: 33 },
    { name: 'Halmahera Timur', provinceId: 33 },
    { name: 'Halmahera Utara', provinceId: 33 },
    { name: 'Pulau Morotai', provinceId: 33 },
    { name: 'Kepulauan Sula', provinceId: 33 },
    { name: 'Nggele', provinceId: 33 },
    { name: 'Pulau Taliabu', provinceId: 33 },
    { name: 'Tidore Kepulauan', provinceId: 33 },
    { name: 'Makassar', provinceId: 34 },
    { name: 'Bantaeng', provinceId: 34 },
    { name: 'Barru', provinceId: 34 },
    { name: 'Bulukumba', provinceId: 34 },
    { name: 'Enrekang', provinceId: 34 },
    { name: 'Jeneponto', provinceId: 34 },
    { name: 'Tana Toraja', provinceId: 34 },
    { name: 'Toraja Utara', provinceId: 34 },
    { name: 'Balusu', provinceId: 34 },
    { name: 'Mamuju', provinceId: 35 },
    { name: 'Mamuju Tengah', provinceId: 35 },
    { name: 'Maros', provinceId: 34 },
    { name: 'Cenrana', provinceId: 34 },
    { name: 'Majene', provinceId: 34 },
    { name: 'Palopo', provinceId: 34 },
    { name: 'Pinrang', provinceId: 34 },
    { name: 'Polewali Mandar', provinceId: 35 },
    { name: 'Sidenreng', provinceId: 34 },
    { name: 'Sidenreng Rappang', provinceId: 34 },
    { name: 'Sidrap', provinceId: 34 },
    { name: 'Sengkang', provinceId: 34 },
    { name: 'Wajo', provinceId: 34 },
    { name: 'Sinjai', provinceId: 34 },
    { name: 'Sungguminasa', provinceId: 34 },
    { name: 'Gowa', provinceId: 34 },
    { name: 'Takalar', provinceId: 34 },
    { name: 'Watampone', provinceId: 34 },
    { name: 'Bone', provinceId: 34 },
    { name: 'Watansoppeng', provinceId: 34 },
    { name: 'Soppeng', provinceId: 34 },
    { name: 'Kepulauan Selayar', provinceId: 34 },
    { name: 'Pangkajene Kepulauan', provinceId: 34 },
    { name: 'Kalukuang Masalima', provinceId: 34 },
    { name: 'Pare-Pare', provinceId: 34 },
    { name: 'Parepare', provinceId: 34 },
    { name: 'Luwu', provinceId: 34 },
    { name: 'Luwu Timur', provinceId: 34 },
    { name: 'Luwu Utara', provinceId: 34 },
    { name: 'Mamasa', provinceId: 35 },
    { name: 'Mamuju Utara', provinceId: 35 }
  ];

  await prisma.cities.createMany({
    data: source
  });
}
