import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function cities() {
  console.log('🔃 Starting Seeds Cities.seeds.ts...');
  await prisma.cities.deleteMany();
  await prisma.$executeRaw`ALTER TABLE Cities AUTO_INCREMENT = 1`;

  const source = [
    { name: 'Aceh Barat', provinceId: 1 },
    { name: 'Aceh Barat Daya', provinceId: 1 },
    { name: 'Aceh Besar', provinceId: 1 },
    { name: 'Aceh Jaya', provinceId: 1 },
    { name: 'Aceh Selatan', provinceId: 1 },
    { name: 'Aceh Singkil', provinceId: 1 },
    { name: 'Aceh Tamiang', provinceId: 1 },
    { name: 'Aceh Tengah', provinceId: 1 },
    { name: 'Aceh Tenggara', provinceId: 1 },
    { name: 'Aceh Timur', provinceId: 1 },
    { name: 'Aceh Utara', provinceId: 1 },
    { name: 'Bener Meriah', provinceId: 1 },
    { name: 'Bireuen', provinceId: 1 },
    { name: 'Gayo Lues', provinceId: 1 },
    { name: 'Nagan Raya', provinceId: 1 },
    { name: 'Pidie', provinceId: 1 },
    { name: 'Pidie Jaya', provinceId: 1 },
    { name: 'Simeulue', provinceId: 1 },
    { name: 'Banda Aceh', provinceId: 1 },
    { name: 'Langsa', provinceId: 1 },
    { name: 'Lhokseumawe', provinceId: 1 },
    { name: 'Sabang', provinceId: 1 },
    { name: 'Subulussalam', provinceId: 1 },
    { name: 'Badung', provinceId: 2 },
    { name: 'Bangli', provinceId: 2 },
    { name: 'Buleleng', provinceId: 2 },
    { name: 'Gianyar', provinceId: 2 },
    { name: 'Jembrana', provinceId: 2 },
    { name: 'Karangasem', provinceId: 2 },
    { name: 'Klungkung', provinceId: 2 },
    { name: 'Tabanan', provinceId: 2 },
    { name: 'Denpasar', provinceId: 2 },
    { name: 'Lebak', provinceId: 3 },
    { name: 'Pandeglang', provinceId: 3 },
    { name: 'Serang', provinceId: 3 },
    { name: 'Tangerang', provinceId: 3 },
    { name: 'Cilegon', provinceId: 3 },
    { name: 'Serang', provinceId: 3 },
    { name: 'Tangerang', provinceId: 3 },
    { name: 'Tangerang Selatan', provinceId: 3 },
    { name: 'Bengkulu Selatan', provinceId: 4 },
    { name: 'Bengkulu Tengah', provinceId: 4 },
    { name: 'Bengkulu Utara', provinceId: 4 },
    { name: 'Kaur', provinceId: 4 },
    { name: 'Kepahiang', provinceId: 4 },
    { name: 'Lebong', provinceId: 4 },
    { name: 'Mukomuko', provinceId: 4 },
    { name: 'Rejang Lebong', provinceId: 4 },
    { name: 'Seluma', provinceId: 4 },
    { name: 'Bengkulu', provinceId: 4 },
    { name: 'Bantul', provinceId: 5 },
    { name: 'Gunungkidul', provinceId: 5 },
    { name: 'Kulon Progo', provinceId: 5 },
    { name: 'Sleman', provinceId: 5 },
    { name: 'Yogyakarta', provinceId: 5 },
    { name: 'Kepulauan Seribu', provinceId: 6 },
    { name: 'Jakarta Barat', provinceId: 6 },
    { name: 'Jakarta Pusat', provinceId: 6 },
    { name: 'Jakarta Selatan', provinceId: 6 },
    { name: 'Jakarta Timur', provinceId: 6 },
    { name: 'Jakarta Utara', provinceId: 6 },
    { name: 'Boalemo', provinceId: 7 },
    { name: 'Bone Bolango', provinceId: 7 },
    { name: 'Gorontalo', provinceId: 7 },
    { name: 'Gorontalo Utara', provinceId: 7 },
    { name: 'Pohuwato', provinceId: 7 },
    { name: 'Gorontalo', provinceId: 7 },
    { name: 'Merangin', provinceId: 8 },
    { name: 'Muaro Jambi', provinceId: 8 },
    { name: 'Batanghari', provinceId: 8 },
    { name: 'Bungo', provinceId: 8 },
    { name: 'Kerinci', provinceId: 8 },
    { name: 'Sarolangun', provinceId: 8 },
    { name: 'Tanjung Jabung Barat', provinceId: 8 },
    { name: 'Tanjung Jabung Timur', provinceId: 8 },
    { name: 'Tebo', provinceId: 8 },
    { name: 'Jambi', provinceId: 8 },
    { name: 'Sungai Penuh', provinceId: 8 },
    { name: 'Bandung', provinceId: 9 },
    { name: 'Bandung Barat', provinceId: 9 },
    { name: 'Bekasi', provinceId: 9 },
    { name: 'Bogor', provinceId: 9 },
    { name: 'Ciamis', provinceId: 9 },
    { name: 'Cianjur', provinceId: 9 },
    { name: 'Cirebon', provinceId: 9 },
    { name: 'Garut', provinceId: 9 },
    { name: 'Indramayu', provinceId: 9 },
    { name: 'Karawang', provinceId: 9 },
    { name: 'Kuningan', provinceId: 9 },
    { name: 'Majalengka', provinceId: 9 },
    { name: 'Pangandaran', provinceId: 9 },
    { name: 'Purwakarta', provinceId: 9 },
    { name: 'Subang', provinceId: 9 },
    { name: 'Sukabumi', provinceId: 9 },
    { name: 'Sumedang', provinceId: 9 },
    { name: 'Tasikmalaya', provinceId: 9 },
    { name: 'Banjar', provinceId: 9 },
    { name: 'Cimahi', provinceId: 9 },
    { name: 'Depok', provinceId: 9 },
    { name: 'Banjarnegara', provinceId: 10 },
    { name: 'Banyumas', provinceId: 10 },
    { name: 'Batang', provinceId: 10 },
    { name: 'Blora', provinceId: 10 },
    { name: 'Boyolali', provinceId: 10 },
    { name: 'Brebes', provinceId: 10 },
    { name: 'Cilacap', provinceId: 10 },
    { name: 'Demak', provinceId: 10 },
    { name: 'Grobogan', provinceId: 10 },
    { name: 'Jepara', provinceId: 10 },
    { name: 'Karanganyar', provinceId: 10 },
    { name: 'Kebumen', provinceId: 10 },
    { name: 'Kendal', provinceId: 10 },
    { name: 'Klaten', provinceId: 10 },
    { name: 'Kudus', provinceId: 10 },
    { name: 'Magelang', provinceId: 10 },
    { name: 'Pati', provinceId: 10 },
    { name: 'Pekalongan', provinceId: 10 },
    { name: 'Pemalang', provinceId: 10 },
    { name: 'Purbalingga', provinceId: 10 },
    { name: 'Purworejo', provinceId: 10 },
    { name: 'Rembang', provinceId: 10 },
    { name: 'Semarang', provinceId: 10 },
    { name: 'Sragen', provinceId: 10 },
    { name: 'Sukoharjo', provinceId: 10 },
    { name: 'Tegal', provinceId: 10 },
    { name: 'Temanggung', provinceId: 10 },
    { name: 'Wonogiri', provinceId: 10 },
    { name: 'Wonosobo', provinceId: 10 },
    { name: 'Magelang', provinceId: 10 },
    { name: 'Pekalongan', provinceId: 10 },
    { name: 'Salatiga', provinceId: 10 },
    { name: 'Semarang', provinceId: 10 },
    { name: 'Surakarta', provinceId: 10 },
    { name: 'Tegal', provinceId: 10 },
    { name: 'Bangkalan', provinceId: 11 },
    { name: 'Banyuwangi', provinceId: 11 },
    { name: 'Blitar', provinceId: 11 },
    { name: 'Bojonegoro', provinceId: 11 },
    { name: 'Bondowoso', provinceId: 11 },
    { name: 'Gresik', provinceId: 11 },
    { name: 'Jember', provinceId: 11 },
    { name: 'Jombang', provinceId: 11 },
    { name: 'Kediri', provinceId: 11 },
    { name: 'Lamongan', provinceId: 11 },
    { name: 'Lumajang', provinceId: 11 },
    { name: 'Madiun', provinceId: 11 },
    { name: 'Magetan', provinceId: 11 },
    { name: 'Malang', provinceId: 11 },
    { name: 'Mojokerto', provinceId: 11 },
    { name: 'Nganjuk', provinceId: 11 },
    { name: 'Ngawi', provinceId: 11 },
    { name: 'Pacitan', provinceId: 11 },
    { name: 'Pamekasan', provinceId: 11 },
    { name: 'Pasuruan', provinceId: 11 },
    { name: 'Ponorogo', provinceId: 11 },
    { name: 'Probolinggo', provinceId: 11 },
    { name: 'Sampang', provinceId: 11 },
    { name: 'Sidoarjo', provinceId: 11 },
    { name: 'Situbondo', provinceId: 11 },
    { name: 'Sumenep', provinceId: 11 },
    { name: 'Trenggalek', provinceId: 11 },
    { name: 'Tuban', provinceId: 11 },
    { name: 'Tulungagung', provinceId: 11 },
    { name: 'Batu', provinceId: 11 },
    { name: 'Blitar', provinceId: 11 },
    { name: 'Kediri', provinceId: 11 },
    { name: 'Madiun', provinceId: 11 },
    { name: 'Malang', provinceId: 11 },
    { name: 'Mojokerto', provinceId: 11 },
    { name: 'Pasuruan', provinceId: 11 },
    { name: 'Probolinggo', provinceId: 11 },
    { name: 'Surabaya', provinceId: 11 },
    { name: 'Bengkayang', provinceId: 12 },
    { name: 'Kapuas Hulu', provinceId: 12 },
    { name: 'Kayong Utara', provinceId: 12 },
    { name: 'Ketapang', provinceId: 12 },
    { name: 'Kubu Raya', provinceId: 12 },
    { name: 'Landak', provinceId: 12 },
    { name: 'Melawi', provinceId: 12 },
    { name: 'Mempawah', provinceId: 12 },
    { name: 'Sambas', provinceId: 12 },
    { name: 'Sanggau', provinceId: 12 },
    { name: 'Sekadau', provinceId: 12 },
    { name: 'Sintang', provinceId: 12 },
    { name: 'Pontianak', provinceId: 12 },
    { name: 'Singkawang', provinceId: 12 },
    { name: 'Balangan', provinceId: 13 },
    { name: 'Banjar', provinceId: 13 },
    { name: 'Barito Kuala', provinceId: 13 },
    { name: 'Hulu Sungai Selatan', provinceId: 13 },
    { name: 'Hulu Sungai Tengah', provinceId: 13 },
    { name: 'Hulu Sungai Utara', provinceId: 13 },
    { name: 'Kotabaru', provinceId: 13 },
    { name: 'Tabalong', provinceId: 13 },
    { name: 'Tanah Bumbu', provinceId: 13 },
    { name: 'Tanah Laut', provinceId: 13 },
    { name: 'Tapin', provinceId: 13 },
    { name: 'Banjarbaru', provinceId: 13 },
    { name: 'Banjarmasin', provinceId: 13 },
    { name: 'Barito Selatan', provinceId: 14 },
    { name: 'Barito Timur', provinceId: 14 },
    { name: 'Barito Utara', provinceId: 14 },
    { name: 'Gunung Mas', provinceId: 14 },
    { name: 'Kapuas', provinceId: 14 },
    { name: 'Katingan', provinceId: 14 },
    { name: 'Kotawaringin Barat', provinceId: 14 },
    { name: 'Kotawaringin Timur', provinceId: 14 },
    { name: 'Lamandau', provinceId: 14 },
    { name: 'Murung Raya', provinceId: 14 },
    { name: 'Pulang Pisau', provinceId: 14 },
    { name: 'Seruyan', provinceId: 14 },
    { name: 'Sukamara', provinceId: 14 },
    { name: 'Palangkaraya', provinceId: 14 },
    { name: 'Berau', provinceId: 15 },
    { name: 'Kutai Barat', provinceId: 15 },
    { name: 'Kutai Kartanegara', provinceId: 15 },
    { name: 'Kutai Timur', provinceId: 15 },
    { name: 'Mahakam Ulu', provinceId: 15 },
    { name: 'Paser', provinceId: 15 },
    { name: 'Penajam Paser Utara', provinceId: 15 },
    { name: 'Balikpapan', provinceId: 15 },
    { name: 'Bontang', provinceId: 15 },
    { name: 'Samarinda', provinceId: 15 },
    { name: 'Bulungan', provinceId: 16 },
    { name: 'Malinau', provinceId: 16 },
    { name: 'Nunukan', provinceId: 16 },
    { name: 'Tana Tidung', provinceId: 16 },
    { name: 'Tarakan', provinceId: 16 },
    { name: 'Bangka', provinceId: 17 },
    { name: 'Bangka Barat', provinceId: 17 },
    { name: 'Bangka Selatan', provinceId: 17 },
    { name: 'Bangka Tengah', provinceId: 17 },
    { name: 'Belitung', provinceId: 17 },
    { name: 'Belitung Timur', provinceId: 17 },
    { name: 'Pangkal Pinang', provinceId: 17 },
    { name: 'Bintan', provinceId: 18 },
    { name: 'Karimun', provinceId: 18 },
    { name: 'Kepulauan Anambas', provinceId: 18 },
    { name: 'Lingga', provinceId: 18 },
    { name: 'Natuna', provinceId: 18 },
    { name: 'Batam', provinceId: 18 },
    { name: 'Tanjung Pinang', provinceId: 18 }
  ];

  await prisma.cities.createMany({
    data: source
  });
}
